version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      - db_name=ecommerce
      - db_user=postgress
      - db_password=1111
      - db_host=db
      - db_port=5432
    volumes:
      - .:/app
  db:
    image: postgres
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=postgress
      - POSTGRES_PASSWORD=1111
