version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=ecommerce
      - DB_USER=postgress
      - DB_PASSWORD=1111
      - .:/app
      - ./nginx.conf:/etc/nginx/sites-available/default
      # - ./supervisor.conf:/etc/supervisor/conf.d/
    command: bash -c "python src/manage.py migrate && gunicorn django.core.wsgi:get_wsgi_application --bind 0.0.0.0:8000"
    # command: gunicorn django.core.wsgi:get_wsgi_application --bind 0.0.0.0:8000


  db:
    image: postgres
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=postgress
      - POSTGRES_PASSWORD=1111
  nginx:
    image: nginx
    ports:
      - '8100:80'
    volumes:
      - ./nginx.conf:/etc/nginx/sites-available/default
    depends_on:
      - web
