# Generated by Django 4.2.2 on 2023-06-17 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_cartitem_product_alter_cartitem_user_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Order", "verbose_name_plural": "Orders"},
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="order",
            name="quantity",
        ),
    ]
